let gameData = {
    reward: null,
    startedBy: null,
    players: [],
    topic: null,
    currentPlayerId: null,
    currentQuestionTimeout: null,
    timeLimit: 30,
    questionTime: 15,
    isGameRunning: false,
    isJoiningAllowed: false,
    shuffledOptions: null,
    questions: [],
    topics: {
        javascript: [
            { question: 'ما هي البيئة التطويرية الرسمية لبرمجة جافا سكريبت؟', options: ['Visual Studio Code', 'Eclipse', 'NetBeans'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء متغير في جافا سكريبت؟', options: ['let', 'var', 'const'], correct: 0 },
            { question: 'ما هو النوع الافتراضي للمتغير في جافا سكريبت؟', options: ['object', 'string', 'number'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لطباعة النص في جافا سكريبت؟', options: ['print()', 'console.log()', 'echo()'], correct: 1 },
            { question: 'ما هو النوع الذي يُستخدم للتعبير عن مجموعة غير محدودة من القيم في جافا سكريبت؟', options: ['array', 'set', 'object'], correct: 0 },
            { question: 'ما هي الدالة لإنشاء مصفوفة جديدة في جافا سكريبت؟', options: ['new()', 'array()', 'make()'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لاستخدام المتغيرات العامة في جافا سكريبت؟', options: ['public', 'private', 'global'], correct: 2 },
            { question: 'ما هي الدالة لاختبار تساوي القيم في جافا سكريبت؟', options: ['==', 'equals()', 'is'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت الأكثر استخدامًا للتعامل مع الرسوم البيانية؟', options: ['D3.js', 'jQuery', 'React'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت المستخدمة للتفاعل مع الخوادم؟', options: ['Axios', 'Fetch', 'jQuery'], correct: 0 },
            { question: 'ما هي الدالة لاختبار وجود عنصر في مصفوفة في جافا سكريبت؟', options: ['includes()', 'find()', 'indexOf()'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت التي تُستخدم لتحليل JSON؟', options: ['JSON.parse()', 'JSON.stringify()', 'JSON.read()'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة في جافا سكريبت؟', options: ['function', 'def', 'make()'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت المستخدمة لتصميم صفحات الويب الديناميكية؟', options: ['Angular', 'Vue.js', 'React'], correct: 2 },
            { question: 'ما هي الدالة لاختبار الفروق بين كائنين في جافا سكريبت؟', options: ['diff()', 'compare()', '==='], correct: 2 },
            { question: 'ما هي المكتبة التي تُستخدم لإنشاء الرسوم البيانية التفاعلية في جافا سكريبت؟', options: ['D3.js', 'Chart.js', 'jQuery'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لتنفيذ عمليات رياضية مثل الجمع والطرح في جافا سكريبت؟', options: ['Math()', 'calculate()', 'compute()'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت الأكثر شيوعًا للتعامل مع التفاعلات بين العميل والخادم؟', options: ['Axios', 'Fetch', 'jQuery'], correct: 1 },
            { question: 'ما هي طريقة الوصول إلى عناصر النموذج في جافا سكريبت؟', options: ['getElementById()', 'find()', 'querySelector()'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت التي تُستخدم لبناء واجهات المستخدم التفاعلية؟', options: ['React', 'Vue.js', 'Angular'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة غير متغيرة في جافا سكريبت؟', options: ['function', 'const', 'readonly'], correct: 1 },
            { question: 'ما هي الدالة المستخدمة للتحقق من نوع البيانات في جافا سكريبت؟', options: ['typeof', 'isType()', 'checkType()'], correct: 0 },
            { question: 'ما هي المكتبة التي تُستخدم لتنظيم السلاسل النصية في جافا سكريبت؟', options: ['lodash', 'jQuery', 'React'], correct: 0 },
            { question: 'ما هي الطريقة لاستخدام الرموز في جافا سكريبت؟', options: ['symbols', 'enum', 'keys'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر استخدامًا لإنشاء الرسوم البيانية التفاعلية في جافا سكريبت؟', options: ['D3.js', 'Chart.js', 'jQuery'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الفئات في جافا سكريبت؟', options: ['class', 'extends', 'constructor'], correct: 0 },
            { question: 'ما هي الدالة لاختبار وجود العنصر في مصفوفة في جافا سكريبت؟', options: ['indexOf()', 'includes()', 'find()'], correct: 1 },
            { question: 'ما هي مكتبة جافا سكريبت المستخدمة لإنشاء الرسوم البيانية التفاعلية؟', options: ['Chart.js', 'D3.js', 'jQuery'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لتحويل النصوص الكبيرة إلى صيغ أصغر في جافا سكريبت؟', options: ['toLowerCase()', 'toUpperCase()', 'trim()'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت الأكثر استخدامًا لإنشاء التطبيقات متعددة الخيوط؟', options: ['Web Workers', 'Axios', 'jQuery'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء كائن جديد في جافا سكريبت؟', options: ['new', 'make()', 'create'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت المستخدمة لإجراء العمليات الحسابية الجبرية؟', options: ['math.js', 'compute()', 'calculate()'], correct: 0 },
            { question: 'ما هي الدالة لاختبار الفروق بين القيم في جافا سكريبت؟', options: ['===', 'compare()', 'equal()'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لتحديد مجال الرؤية في جافا سكريبت؟', options: ['let', 'var', 'const'], correct: 2 },
            { question: 'ما هي مكتبة جافا سكريبت الأكثر استخدامًا لتنفيذ التفاعلات الرسومية؟', options: ['D3.js', 'Chart.js', 'jQuery'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لتحويل النصوص الكبيرة إلى صيغ أصغر في جافا سكريبت؟', options: ['toLowerCase()', 'toUpperCase()', 'trim()'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت المستخدمة لبناء صفحات الويب الديناميكية؟', options: ['Angular', 'Vue.js', 'React'], correct: 2 },
            { question: 'ما هي المكتبة التي تُستخدم لتحليل JSON في جافا سكريبت؟', options: ['JSON.parse()', 'JSON.stringify()', 'JSON.read()'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة ثابتة في جافا سكريبت؟', options: ['function', 'const', 'readonly'], correct: 1 },
            { question: 'ما هي الطريقة لاستخدام JSON في جافا سكريبت؟', options: ['JSON.parse()', 'JSON.stringify()', 'JSON.read()'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت التي تُستخدم لبناء تطبيقات الهواتف الذكية؟', options: ['React Native', 'PhoneGap', 'Flutter'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت الأكثر استخدامًا لتحليل البيانات؟', options: ['D3.js', 'Chart.js', 'jQuery'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة غير قابلة للتغيير في جافا سكريبت؟', options: ['function', 'const', 'readonly'], correct: 1 },
            { question: 'ما هي الطريقة لاستخدام دالة المطابقة في جافا سكريبت؟', options: ['match()', 'test()', 'search()'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت التي تُستخدم لإنشاء الرسوم البيانية؟', options: ['Chart.js', 'D3.js', 'jQuery'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء متغير غير قابل للتغيير في جافا سكريبت؟', options: ['const', 'readonly', 'immutable'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت الأكثر استخدامًا لبناء واجهات المستخدم التفاعلية؟', options: ['React', 'Vue.js', 'Angular'], correct: 0 },
            { question: 'ما هي الدالة التي تُستخدم لتنفيذ عمليات رياضية مثل الجمع والطرح في جافا سكريبت؟', options: ['Math()', 'calculate()', 'compute()'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لتحديد نطاق الرؤية في جافا سكريبت؟', options: ['let', 'var', 'const'], correct: 2 },
            { question: 'ما هي مكتبة جافا سكريبت التي تُستخدم لتحليل النصوص؟', options: ['NLTK', 'Lodash', 'jQuery'], correct: 1 },
            { question: 'ما هي مكتبة جافا سكريبت المستخدمة لإنشاء الرسوم البيانية؟', options: ['D3.js', 'Chart.js', 'jQuery'], correct: 0 },
            { question: 'ما هي الدالة التي تُستخدم للتحقق من نوع البيانات في جافا سكريبت؟', options: ['typeof', 'isType()', 'checkType()'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة غير قابلة للتغيير في جافا سكريبت؟', options: ['function', 'const', 'readonly'], correct: 1 },
            { question: 'ما هي مكتبة جافا سكريبت التي تُستخدم لبناء تطبيقات الهواتف الذكية؟', options: ['React Native', 'PhoneGap', 'Flutter'], correct: 0 },
            { question: 'ما هي مكتبة جافا سكريبت المستخدمة لبناء الرسوم البيانية؟', options: ['Chart.js', 'D3.js', 'jQuery'], correct: 0 }
        ]
        ,
        csharp: [
            { question: 'ما هي البيئة التطويرية الرسمية لبرمجة C#؟', options: ['Visual Studio', 'Eclipse', 'NetBeans'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء متغير في C#؟', options: ['var', 'let', 'const'], correct: 0 },
            { question: 'ما هو النوع الافتراضي للمتغير في C#؟', options: ['int', 'object', 'string'], correct: 1 },
            { question: 'ما هي الدالة المستخدمة لطباعة النص في C#؟', options: ['print()', 'Console.WriteLine()', 'echo()'], correct: 1 },
            { question: 'ما هو النوع الذي يُستخدم للتعبير عن مجموعة غير محدودة من القيم في C#؟', options: ['List', 'Array', 'HashSet'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء مصفوفة في C#؟', options: ['new()', 'make()', 'array()'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر شيوعًا في C# للتعامل مع قواعد البيانات؟', options: ['Entity Framework', 'ADO.NET', 'Dapper'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء متغير ثابت في C#؟', options: ['readonly', 'const', 'immutable'], correct: 0 },
            { question: 'ما هي الدالة لاختبار تساوي القيم في C#؟', options: ['==', 'equals()', 'compare()'], correct: 0 },
            { question: 'ما هي مكتبة C# المستخدمة لتنفيذ العمليات الحسابية الجبرية؟', options: ['Math.NET', 'NMath', 'Math.Finance'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الوراثة في C#؟', options: ['inherit', 'extends', 'class'], correct: 2 },
            { question: 'ما هي الدالة المستخدمة لتنظيم المصفوفة في C#؟', options: ['Sort()', 'Order()', 'Arrange()'], correct: 0 },
            { question: 'ما هي المكتبة المستخدمة لتنظيم الذاكرة في C#؟', options: ['malloc()', 'new', 'calloc()'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الدوال الخفية في C#؟', options: ['private', 'protected', 'static'], correct: 2 },
            { question: 'ما هي المكتبة التي تُستخدم لإنشاء الواجهات الرسومية في C#؟', options: ['Windows Forms', 'WPF', 'Gtk#'], correct: 1 },
            { question: 'ما هي المكتبة الأكثر شيوعًا في C# لتنفيذ التعليمات البرمجية الخاصة باللوائح؟', options: ['System.IO', 'System.Xml', 'System.Linq'], correct: 2 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة ثابتة في C#؟', options: ['static', 'const', 'readonly'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الفئات العامة في C#؟', options: ['public', 'protected', 'private'], correct: 0 },
            { question: 'ما هي مكتبة C# المستخدمة لتنظيم البيانات؟', options: ['Linq', 'Dapper', 'Entity Framework'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة غير قابلة للتغيير في C#؟', options: ['readonly', 'const', 'static'], correct: 1 },
            { question: 'ما هي مكتبة C# المستخدمة للتعامل مع JSON؟', options: ['Json.NET', 'System.Json', 'Newtonsoft.Json'], correct: 2 },
            { question: 'ما هي مكتبة C# المستخدمة لبناء صفحات ويب؟', options: ['ASP.NET', 'MVC', 'Web API'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء حلقة تكرارية غير محدودة في C#؟', options: ['for', 'while', 'do'], correct: 2 },
            { question: 'ما هي المكتبة الأكثر شيوعًا في C# لإنشاء الرسوم البيانية؟', options: ['OxyPlot', 'Windows Forms', 'WPF'], correct: 0 },
            { question: 'ما هي المكتبة التي تُستخدم لتنظيم النصوص في C#؟', options: ['StringBuilder', 'Regex', 'Linq'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر استخدامًا في C# لتنفيذ التعليمات البرمجية الخاصة بإدارة الوقت؟', options: ['Noda Time', 'TimeSpan', 'DateTime'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الدوال العامة في C#؟', options: ['public', 'private', 'protected'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء نوع بيانات غير قابل للتغيير في C#؟', options: ['readonly', 'const', 'immutable'], correct: 2 },
            { question: 'ما هي المكتبة الأكثر شيوعًا في C# لتنفيذ البرمجة الخاصة بالبنية التحتية؟', options: ['Entity Framework', 'Dapper', 'Linq'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء كائن جديد في C#؟', options: ['new', 'make()', 'create()'], correct: 0 },
            { question: 'ما هي مكتبة C# المستخدمة لتنفيذ عمليات التحليل الإحصائي؟', options: ['Math.NET', 'NumPy', 'SciPy'], correct: 0 },
            { question: 'ما هي الدالة لاختبار وجود عنصر في مجموعة في C#؟', options: ['Contains()', 'find()', 'indexOf()'], correct: 0 },
            { question: 'ما هي مكتبة C# الأكثر شيوعًا لتنفيذ التحليل البياني؟', options: ['OxyPlot', 'Chart.js', 'D3.js'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لتحويل الجملة إلى حرف صغير في C#؟', options: ['ToLower()', 'ToUpper()', 'ToTitleCase()'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر شيوعًا في C# لتنفيذ التعليمات البرمجية الخاصة بالبيانات الضخمة؟', options: ['ML.NET', 'WPF', 'Entity Framework'], correct: 0 },
            { question: 'ما هي الدالة التي تُستخدم للتحقق من نوع البيانات في C#؟', options: ['typeof()', 'isType()', 'checkType()'], correct: 0 },
            { question: 'ما هي مكتبة C# التي تُستخدم لإنشاء تطبيقات الهاتف المحمول؟', options: ['Xamarin', 'Cordova', 'PhoneGap'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر استخدامًا في C# لبناء تطبيقات الويب الديناميكية؟', options: ['ASP.NET', 'MVC', 'Web API'], correct: 0 },
            { question: 'ما هي الدالة لاختبار الفروق بين كائنين في C#؟', options: ['Equals()', 'Compare()', 'IsEqual()'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر شيوعًا في C# لتنفيذ البرمجة الكمية؟', options: ['Math.NET', 'NMath', 'Dapper'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة غير قابلة للتغيير في C#؟', options: ['readonly', 'const', 'static'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لإنشاء متغير ثابت في C#؟', options: ['readonly', 'const', 'immutable'], correct: 0 },
            { question: 'ما هي مكتبة C# المستخدمة لتنفيذ البرمجة الخاصة بالبيانات الضخمة؟', options: ['ML.NET', 'WPF', 'Entity Framework'], correct: 0 },
            { question: 'ما هي الدالة لاختبار وجود العنصر في مجموعة في C#؟', options: ['Contains()', 'find()', 'indexOf()'], correct: 0 },
            { question: 'ما هي مكتبة C# المستخدمة لتحليل البيانات؟', options: ['Json.NET', 'Linq', 'Dapper'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر استخدامًا في C# لتنفيذ البرمجة الموجهة للكائنات؟', options: ['Entity Framework', 'Dapper', 'Linq'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لطباعة النص في C#؟', options: ['print()', 'Console.WriteLine()', 'echo()'], correct: 1 }
        ]
        ,
        python: [
            { question: 'ما هي البيئة التطويرية الرسمية لبرمجة بايثون؟', options: ['PyCharm', 'Eclipse', 'Visual Studio'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة في بايثون؟', options: ['def', 'function', 'make'], correct: 0 },
            { question: 'ما هو النوع الافتراضي للمتغير في بايثون؟', options: ['int', 'float', 'object'], correct: 2 },
            { question: 'ما هي طريقة الطباعة في بايثون؟', options: ['print()', 'echo()', 'display()'], correct: 0 },
            { question: 'ما هو النوع الذي يستخدم للتعبير عن مجموعة غير محدودة من القيم في بايثون؟', options: ['list', 'set', 'dict'], correct: 1 },
            { question: 'ما هي الدالة المستخدمة لإنشاء قائمة جديدة في بايثون؟', options: ['new()', 'list()', 'make()'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لاستخدام المتغيرات العامة في بايثون؟', options: ['public', 'private', 'global'], correct: 2 },
            { question: 'ما هي الدالة لاختبار تساوي القيم في بايثون؟', options: ['==', 'equals()', 'is'], correct: 0 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لتحليل البيانات؟', options: ['Pandas', 'NumPy', 'SciPy'], correct: 0 },
            { question: 'ما هي مكتبة بايثون المستخدمة للتعامل مع الصور؟', options: ['Pillow', 'OpenCV', 'Matplotlib'], correct: 0 },
            { question: 'ما هي مكتبة بايثون الأكثر استخدامًا لتحليل النصوص؟', options: ['NLTK', 'Scikit-learn', 'SpaCy'], correct: 0 },
            { question: 'ما هي طريقة الحصول على طول سلسلة نصية في بايثون؟', options: ['length()', 'len()', 'size()'], correct: 1 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لتنظيم المصفوفات؟', options: ['NumPy', 'Pandas', 'SciPy'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء كائن جديد في بايثون؟', options: ['new', 'make()', 'create'], correct: 1 },
            { question: 'ما هي الدالة لاختبار الفروق بين كائنين في بايثون؟', options: ['diff()', 'compare()', '=='], correct: 1 },
            { question: 'ما هي مكتبة بايثون الأكثر شيوعًا لتحليل البيانات المكانية؟', options: ['Shapely', 'Pandas', 'Matplotlib'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الدوال العامة في بايثون؟', options: ['public', 'private', 'global'], correct: 2 },
            { question: 'ما هي مكتبة بايثون المستخدمة لإنشاء الرسومات البيانية؟', options: ['Matplotlib', 'Seaborn', 'Pyplot'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لتحويل السلاسل النصية إلى عدد صحيح في بايثون؟', options: ['int()', 'str()', 'float()'], correct: 0 },
            { question: 'ما هي مكتبة بايثون الأكثر استخدامًا لتنفيذ العمليات الرياضية؟', options: ['NumPy', 'SciPy', 'Pandas'], correct: 0 },
            { question: 'ما هي مكتبة بايثون المستخدمة للتعامل مع جداول البيانات؟', options: ['Pandas', 'NumPy', 'Matplotlib'], correct: 0 },
            { question: 'ما هي الدالة لاختبار الفروق بين القيم في بايثون؟', options: ['diff()', 'compare()', '=='], correct: 1 },
            { question: 'ما هي المكتبة التي تستخدم للتعامل مع تواريخ في بايثون؟', options: ['datetime', 'time', 'calendar'], correct: 0 },
            { question: 'ما هي طريقة كتابة حلقة شرطية في بايثون؟', options: ['if', 'while', 'for'], correct: 0 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لإنشاء تطبيقات الويب؟', options: ['Django', 'Flask', 'Pyramid'], correct: 1 },
            { question: 'ما هي الدالة التي تُستخدم لإنشاء جداول البيانات في بايثون؟', options: ['make_table()', 'create_table()', 'pandas.DataFrame()'], correct: 2 },
            { question: 'ما هي طريقة الحصول على الوقت الحالي في بايثون؟', options: ['current_time()', 'time()', 'now()'], correct: 2 },
            { question: 'ما هي مكتبة بايثون الأكثر استخدامًا لتحليل السلاسل النصية؟', options: ['NLTK', 'SpaCy', 'Scikit-learn'], correct: 1 },
            { question: 'ما هي مكتبة بايثون المستخدمة للتعامل مع الجرافيكيات البيانية؟', options: ['Matplotlib', 'Pyplot', 'Seaborn'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء حلقة تكرارية في بايثون؟', options: ['for', 'while', 'repeat'], correct: 0 },
            { question: 'ما هي الدالة التي تُستخدم لتحويل الرقم إلى سلسلة نصية في بايثون؟', options: ['str()', 'int()', 'float()'], correct: 0 },
            { question: 'ما هي مكتبة بايثون المستخدمة للتعامل مع البيانات الجغرافية؟', options: ['Shapely', 'Pandas', 'Matplotlib'], correct: 0 },
            { question: 'ما هي مكتبة بايثون الأكثر استخدامًا لتحليل الصور؟', options: ['Pillow', 'OpenCV', 'Matplotlib'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة غير متغيرة في بايثون؟', options: ['def', 'staticmethod', 'staticmethod'], correct: 1 },
            { question: 'ما هي مكتبة بايثون التي تستخدم لإنشاء واجهات مستخدم؟', options: ['Tkinter', 'Flask', 'Pygame'], correct: 0 },
            { question: 'ما هي الدالة التي تُستخدم للتحقق من وجود عنصر في قائمة في بايثون؟', options: ['in()', 'exists()', 'contains()'], correct: 0 },
            { question: 'ما هي المكتبة التي تُستخدم لتحليل النصوص باستخدام الذكاء الاصطناعي في بايثون؟', options: ['SpaCy', 'NLTK', 'Scikit-learn'], correct: 0 },
            { question: 'ما هي المكتبة التي تستخدم لإنشاء الرسومات البيانية التفاعلية في بايثون؟', options: ['Matplotlib', 'Seaborn', 'Plotly'], correct: 2 },
            { question: 'ما هي الكلمة الأساسية لإنشاء حلقة غير منتهية في بايثون؟', options: ['for', 'while', 'loop'], correct: 1 },
            { question: 'ما هي الدالة التي تُستخدم لتحويل الجملة إلى حرف كبير في بايثون؟', options: ['upper()', 'lower()', 'title()'], correct: 0 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لتحليل الصور الرقمية؟', options: ['Pillow', 'OpenCV', 'Scikit-image'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لإنشاء متغير ثابت في بايثون؟', options: ['const', 'readonly', 'immutable'], correct: 2 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لتحليل البيانات الضخمة؟', options: ['Dask', 'Pandas', 'NumPy'], correct: 0 },
            { question: 'ما هي طريقة الحصول على القيم العشوائية في بايثون؟', options: ['random()', 'shuffle()', 'sample()'], correct: 2 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لإنشاء واجهات مستخدم الرسومية؟', options: ['Tkinter', 'PyQt', 'WxPython'], correct: 0 },
            { question: 'ما هي الدالة التي تُستخدم للتحقق من وجود الملف في بايثون؟', options: ['exists()', 'check()', 'find()'], correct: 0 },
            { question: 'ما هي مكتبة بايثون المستخدمة لتنظيم النصوص؟', options: ['NLTK', 'Scikit-learn', 'Pandas'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء متغير غير قابل للتغيير في بايثون؟', options: ['const', 'readonly', 'immutable'], correct: 2 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لإنشاء رسومات بيانية؟', options: ['Matplotlib', 'Seaborn', 'Pyplot'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء حلقة شرطية في بايثون؟', options: ['if', 'while', 'for'], correct: 0 },
            { question: 'ما هي مكتبة بايثون المستخدمة للتعلم الآلي؟', options: ['Scikit-learn', 'Keras', 'TensorFlow'], correct: 0 },
            { question: 'ما هي مكتبة بايثون المستخدمة لتنفيذ العمليات الحسابية الجبرية؟', options: ['SymPy', 'NumPy', 'Pandas'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لتحويل الجملة إلى حرف صغير في بايثون؟', options: ['lower()', 'upper()', 'title()'], correct: 0 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لتنظيم الجداول؟', options: ['Pandas', 'NumPy', 'SciPy'], correct: 0 },
            { question: 'ما هي الدالة التي تُستخدم لتحويل الرقم إلى سلاسل نصية في بايثون؟', options: ['str()', 'int()', 'float()'], correct: 0 },
            { question: 'ما هي مكتبة بايثون المستخدمة للتعلم العميق؟', options: ['Keras', 'TensorFlow', 'Scikit-learn'], correct: 0 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لتنفيذ عمليات الحسابية المثلثية؟', options: ['math', 'numpy', 'scipy'], correct: 0 },
            { question: 'ما هي المكتبة التي تُستخدم لإنشاء الرسوم البيانية التفاعلية في بايثون؟', options: ['Plotly', 'Seaborn', 'Matplotlib'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الدوال العامة في بايثون؟', options: ['public', 'private', 'global'], correct: 2 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لإنشاء النصوص المكتوبة؟', options: ['NLTK', 'Pandas', 'Scikit-learn'], correct: 0 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لتنفيذ عمليات التحليل الاحصائي؟', options: ['SciPy', 'Pandas', 'NumPy'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لإنشاء دالة ثابتة في بايثون؟', options: ['staticmethod', 'staticmethod()', 'const'], correct: 0 },
            { question: 'ما هي مكتبة بايثون المستخدمة لإنشاء ألعاب؟', options: ['Pygame', 'Tkinter', 'PyQt'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء حلقة تكرارية غير محدودة في بايثون؟', options: ['for', 'while', 'repeat'], correct: 1 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لإنشاء واجهات مستخدم؟', options: ['Tkinter', 'PyQt', 'WxPython'], correct: 0 },
            { question: 'ما هي الدالة التي تُستخدم للتحقق من وجود عنصر في قائمة في بايثون؟', options: ['in()', 'exists()', 'contains()'], correct: 0 },
            { question: 'ما هي مكتبة بايثون التي تُستخدم لإنشاء الرسومات البيانية التفاعلية؟', options: ['Matplotlib', 'Seaborn', 'Plotly'], correct: 2 },
            { question: 'ما هي مكتبة بايثون المستخدمة لإنشاء تقارير البيانات؟', options: ['Pandas', 'NumPy', 'SciPy'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء حلقة شرطية في بايثون؟', options: ['if', 'while', 'for'], correct: 0 },
            { question: 'ما هي مكتبة بايثون الأكثر استخدامًا لإنشاء الواجهات الرسومية؟', options: ['Tkinter', 'PyQt', 'WxPython'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإنشاء متغير ثابت في بايثون؟', options: ['const', 'readonly', 'immutable'], correct: 2 }
        ]
        ,
        cplusplus: [
            { question: 'ما هي بيئة التطوير الرسمية لـ C++؟', options: ['Visual Studio', 'Eclipse', 'NetBeans'], correct: 0 },
            { question: 'ما هو النوع الافتراضي للمصفوفة في C++؟', options: ['Array', 'List', 'Vector'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لإنشاء كائن جديد في C++؟', options: ['new()', 'make()', 'create()'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الوراثة في C++؟', options: ['inherit', 'extends', 'class'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر شيوعًا في C++ للتعامل مع الكائنات؟', options: ['STL', 'Boost', 'Qt'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لإعلان متغير ثابت في C++؟', options: ['const', 'readonly', 'immutable'], correct: 0 },
            { question: 'ما هو النوع الذي يمثل الكائنات في C++؟', options: ['object', 'class', 'struct'], correct: 1 },
            { question: 'ما هي الدالة لاختبار تساوي القيم في C++؟', options: ['==', 'equals()', 'compare()'], correct: 0 },
            { question: 'ما هي مكتبة C++ المستخدمة لتحليل الصور؟', options: ['OpenCV', 'Boost', 'Qt'], correct: 0 },
            { question: 'ما هي الدالة لاختبار وجود عنصر في مصفوفة في C++؟', options: ['contains()', 'in()', 'find()'], correct: 2 },
            { question: 'ما هي الدالة لاختبار وجود كلمة معينة في النص في C++؟', options: ['search()', 'find()', 'test()'], correct: 1 },
            { question: 'ما هي المكتبة المستخدمة لتنظيم الذاكرة في C++؟', options: ['malloc()', 'new', 'calloc()'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الفئات العامة في C++؟', options: ['public', 'protected', 'private'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة لتنظيم المصفوفة في C++؟', options: ['sort()', 'order()', 'arrange()'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الدوال الخفية في C++؟', options: ['private', 'protected', 'static'], correct: 2 },
            { question: 'ما هي المكتبة التي تستخدم لإنشاء الواجهات الرسومية في C++؟', options: ['Qt', 'GTK', 'WinAPI'], correct: 0 },
            { question: 'ما هي الدالة لاختبار الفروق بين كائنين في C++؟', options: ['diff()', 'compare()', 'equal()'], correct: 1 },
            { question: 'ما هي مكتبة C++ التي تُستخدم للتعامل مع السلاسل النصية؟', options: ['Boost', 'STL', 'Regex'], correct: 2 },
            { question: 'ما هو النوع الذي يستخدم لإنشاء الدوال بدون معلمات في C++؟', options: ['void', 'int', 'float'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر استخدامًا لتحليل البيانات في C++؟', options: ['Pandas', 'Boost', 'STL'], correct: 2 },
            { question: 'ما هي وظيفة C++ لاختيار الصدفة العشوائية بين رقمين؟', options: ['rand()', 'random()', 'choose()'], correct: 0 },
            { question: 'ما هي كلمة C++ الأساسية لاختبار الشرط في الدوال؟', options: ['if', 'switch', 'case'], correct: 0 },
            { question: 'ما هي المكتبة التي توفر واجهات مستخدم للبيانات في C++؟', options: ['Qt', 'GTK', 'WinAPI'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام العكس في C++؟', options: ['not', 'true', 'false'], correct: 0 },
            { question: 'ما هي الدالة التي تُستخدم لتنفيذ العمليات الحسابية في C++؟', options: ['calc()', 'math()', 'evaluate()'], correct: 1 },
            { question: 'ما هي المكتبة التي توفر أدوات لتحليل الشيفرات في C++؟', options: ['Boost', 'Regex', 'STL'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الدوال العكوسة في C++؟', options: ['return', 'static', 'final'], correct: 0 },
            { question: 'ما هي الدالة المستخدمة للتحقق من عدد العناصر في مجموعة في C++؟', options: ['size()', 'length()', 'count()'], correct: 0 },
            { question: 'ما هي مكتبة C++ المستخدمة لتحليل البيانات الجغرافية؟', options: ['Boost', 'STL', 'OGR'], correct: 2 },
            { question: 'ما هي وظيفة C++ المستخدمة لإضافة عنصر إلى قائمة؟', options: ['add()', 'push()', 'insert()'], correct: 1 },
            { question: 'ما هي المكتبة التي تستخدم للتعامل مع الرسوم البيانية في C++؟', options: ['Boost', 'STL', 'OpenGL'], correct: 2 },
            { question: 'ما هي الدالة لاختبار وجود عنصر معين في مجموعة؟', options: ['exists()', 'contains()', 'find()'], correct: 1 },
            { question: 'ما هي مكتبة C++ الأكثر شيوعًا لتنفيذ الحسابات الرياضية؟', options: ['STL', 'Boost', 'Eigen'], correct: 2 },
            { question: 'ما هي الكلمة الأساسية لاستخدام المتغيرات العامة في C++؟', options: ['public', 'private', 'protected'], correct: 0 },
            { question: 'ما هي الدالة لاختبار تطابق سلسلتين نصيتين في C++؟', options: ['match()', 'equals()', 'compare()'], correct: 2 },
            { question: 'ما هي المكتبة التي تستخدم للتعامل مع قواعد البيانات في C++؟', options: ['STL', 'SQLite', 'Boost'], correct: 1 },
            { question: 'ما هي كلمة C++ الأساسية لإنشاء الحلقة الشرطية؟', options: ['for', 'while', 'do-while'], correct: 0 },
            { question: 'ما هي المكتبة التي تستخدم لإنشاء واجهات المستخدم في C++؟', options: ['Qt', 'GTK', 'WinAPI'], correct: 0 },
            { question: 'ما هي الدالة لاختبار وجود عنصر في مصفوفة متعددة الأبعاد؟', options: ['multi_find()', 'contains()', 'search()'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لتنفيذ دالة برمجية داخل دالة أخرى في C++؟', options: ['call', 'invoke', 'nested'], correct: 2 },
            { question: 'ما هي الدالة التي تستخدم لإيجاد الفرق بين القيم في C++؟', options: ['difference()', 'subtract()', 'diff()'], correct: 2 },
            { question: 'ما هي المكتبة المستخدمة للتعامل مع تواريخ في C++؟', options: ['Boost.DateTime', 'STL', 'Qt'], correct: 0 },
            { question: 'ما هي كلمة C++ الأساسية لاستخدام التكرار؟', options: ['for', 'while', 'repeat'], correct: 1 },
            { question: 'ما هي الدالة التي تستخدم لفتح ملف في C++؟', options: ['open()', 'read()', 'load()'], correct: 0 },
            { question: 'ما هي المكتبة الأكثر استخدامًا في C++ للتعامل مع الصور؟', options: ['OpenCV', 'STL', 'Boost'], correct: 0 },
            { question: 'ما هي الدالة التي تستخدم لإغلاق ملف في C++؟', options: ['close()', 'exit()', 'unload()'], correct: 0 },
            { question: 'ما هي المكتبة التي توفر أدوات لتحليل السلاسل النصية في C++؟', options: ['Regex', 'STL', 'Boost'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الدوال العامة في C++؟', options: ['public', 'private', 'protected'], correct: 0 },
            { question: 'ما هي مكتبة C++ المستخدمة لإنشاء الرسومات البيانية؟', options: ['OpenGL', 'Boost', 'STL'], correct: 0 },
            { question: 'ما هي الكلمة الأساسية لتحديد التوقيت في C++؟', options: ['time()', 'duration()', 'clock()'], correct: 2 },
            { question: 'ما هي مكتبة C++ الأكثر استخدامًا لإنشاء تطبيقات الطرفية؟', options: ['Boost', 'STL', 'Ncurses'], correct: 2 },
            { question: 'ما هي الدالة لاختبار تطابق السلسلة النصية في C++؟', options: ['matches()', 'equals()', 'compare()'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لاستخدام الوراثة في C++؟', options: ['inherit', 'extends', 'class'], correct: 0 },
            { question: 'ما هي المكتبة التي تستخدم لإنشاء البرامج متعددة الخيوط في C++؟', options: ['Boost', 'STL', 'Threads'], correct: 2 },
            { question: 'ما هي الدالة المستخدمة لحساب القيم المطلقة للعدد في C++؟', options: ['abs()', 'fabs()', 'absolute()'], correct: 0 },
            { question: 'ما هي مكتبة C++ الأكثر شيوعًا للتعامل مع الأنظمة الافتراضية؟', options: ['STL', 'Boost', 'VirtualBox'], correct: 1 },
            { question: 'ما هي الكلمة الأساسية لتحديد أبعاد مصفوفة في C++؟', options: ['length()', 'size()', 'width()'], correct: 1 },
            { question: 'ما هي الدالة المستخدمة لتنفيذ العمليات الحسابية المثلثية في C++؟', options: ['sin()', 'cos()', 'tan()'], correct: 0 },
            { question: 'ما هي مكتبة C++ المستخدمة لتنظيم الأجسام؟', options: ['STL', 'Boost', 'CGAL'], correct: 2 },
            { question: 'ما هي الدالة المستخدمة للتحقق من حالة الخطأ في C++؟', options: ['error()', 'check()', 'errno()'], correct: 2 },
            { question: 'ما هي مكتبة C++ الأكثر شيوعًا للتحليل الآلي؟', options: ['STL', 'Boost', 'ANTLR'], correct: 1 }
        ]
    },
};

function resetGame()
{
    gameData.players = [];
    gameData.currentPlayerId = null;
    gameData.currentQuestionTimeout = null;
    gameData.isGameRunning = false;
    gameData.isJoiningAllowed = false;
    gameData.shuffledOptions = null;
}


module.exports = { gameData, resetGame };
